services:
  go_db:
    container_name: go_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  go-app:
    container_name: go-app
    build: .
    environment:
      host: "go_db"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  

volumes:
  pgdata: {}
